# Библиотека функций генератора кода для Tensor Compiler

require 'json'

module NodeGenerator
    # Маппинг типов: просто возвращаем как есть (из JSON берем полный C++ тип)
    def self.cpp_type(json_type)
        json_type
    end

    # --------------------------------------------------------------------------
    # Генерация заголовочного файла (graph_gen.hpp)
    # --------------------------------------------------------------------------
    def self.write_header_start(f)
        f.puts "// AUTOGENERATED FILE. DO NOT EDIT MANUALLY."
        f.puts "#pragma once"
        f.puts ""
        f.puts '#include <string>'
        f.puts '#include <vector>'
        f.puts '#include <variant>'
        f.puts '#include <cstdint>'
        f.puts ""
        f.puts "namespace tcc {"
        f.puts ""
        f.puts "using TensorID = std::string;"
        f.puts ""
    end

    def self.write_node_struct(f, op, common_fields)
        cpp_name = op['cpp_name']
        f.puts "struct #{cpp_name} {"

        # Общие поля
        if common_fields
        common_fields.each do |field|
            type = cpp_type(field['type'])
            default = field['default']
            f.puts "    #{type} #{field['name']} = #{default};"
        end
        f.puts "" unless (op['attributes'] || []).empty?
        end

        # Специфичные атрибуты
        (op['attributes'] || []).each do |attr|
        type = cpp_type(attr['type'])
        default = attr['default']
        f.puts "    #{type} #{attr['name']} = #{default};"
        end

        f.puts "};"
        f.puts ""
    end

    def self.write_variant_typedef(f, data)
        real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }
        cpp_names = real_ops.map { |op| op['cpp_name'] }.join(', ')
        f.puts "using ComputeNode = std::variant<#{cpp_names}>;"
        f.puts ""
    end

    def self.write_header_end(f)
        f.puts "} // namespace tcc"
    end

    # --------------------------------------------------------------------------
    # Генерация парсера (graph_gen_parser.inl)
    # --------------------------------------------------------------------------
    def self.write_parser_start(f)
        f.puts "// AUTOGENERATED FILE. DO NOT EDIT MANUALLY."
        f.puts "#include \"graph_gen.hpp\""
        f.puts "#include \"onnx/onnx-ml.pb.h\""
        f.puts "#include <stdexcept>"
        f.puts ""
        f.puts "namespace tcc {"
        f.puts ""
    end

    def self.write_parse_attributes_function(f, op)
        cpp_name = op['cpp_name']
        attrs = op['attributes'] || []

        f.puts "inline void parse_attributes(#{cpp_name}& node, const onnx::NodeProto& proto) {"
        f.puts "    for (const auto& attr : proto.attribute()) {"
        f.puts "        const std::string& attr_name = attr.name();"

        if attrs.empty?
        f.puts "        // No attributes"
        else
        f.puts "        if (false) {}"
        attrs.each do |attr|
            name = attr['name']
            type = attr['type']
            f.puts "        else if (attr_name == \"#{name}\") {"

            case type
            when 'bool'
            f.puts "            node.#{name} = attr.has_i() ? (attr.i() != 0) : false;"
            when 'float'
            f.puts "            node.#{name} = attr.f();"
            when 'int64_t'
            f.puts "            node.#{name} = attr.i();"
            when 'std::string'
            f.puts "            node.#{name} = attr.s();"
            when /^std::vector<int64_t>$/
            f.puts "            node.#{name}.assign(attr.ints().begin(), attr.ints().end());"
            when /^std::vector<float>$/
            f.puts "            node.#{name}.assign(attr.floats().begin(), attr.floats().end());"
            else
            f.puts "            // Unsupported type: #{type}"
            end
            f.puts "        }"
        end
        f.puts "        else { /* ignore unknown */ }"
        end
        f.puts "    }"
        f.puts "}"
        f.puts ""
    end

    def self.write_factory_function(f, op, common_fields)
        cpp_name = op['cpp_name']
        onnx_type = op['op_type']
        func_name = "create_#{onnx_type}_node"

        f.puts "inline ComputeNode #{func_name}(const onnx::NodeProto& proto) {"
        f.puts "    #{cpp_name} node;"

        if common_fields
        f.puts "    node.name = proto.name();"
        f.puts "    node.input_tensors.assign(proto.input().begin(), proto.input().end());"
        f.puts "    node.output_tensors.assign(proto.output().begin(), proto.output().end());"
        end

        f.puts "    parse_attributes(node, proto);"
        f.puts "    return node;"
        f.puts "}"
        f.puts ""
    end

    def self.write_dispatcher_function(f, data)
        real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }
        f.puts "inline ComputeNode create_node_from_proto(const onnx::NodeProto& proto) {"
        f.puts "    const std::string& op = proto.op_type();"
        real_ops.each do |op|
        f.puts "    if (op == \"#{op['op_type']}\") return create_#{op['op_type']}_node(proto);"
        end
        f.puts "    throw std::runtime_error(\"Unsupported operator: \" + op);"
        f.puts "}"
        f.puts ""
    end

    def self.write_parser_end(f)
        f.puts "} // namespace tcc"
    end

   def self.write_dot_helper_function(f, data, common_fields)
    real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }

    colors = {
      "Add" => "#E3F2FD", "Mul" => "#E8F5E9", "Relu" => "#FFF3E0",
      "MatMul" => "#F3E5F5", "Gemm" => "#EFEBE9", "Conv" => "#E0F7FA",
      "Constant" => "#FAFAFA", "Reshape" => "#FFFDE7", "Transpose" => "#FCE4EC",
      "Unknown" => "#EEEEEE"
    }

    f.puts "// AUTOGENERATED DOT HELPER. DO NOT EDIT."
    f.puts "#include <sstream>"
    f.puts "#include <string>"
    f.puts "#include <algorithm>"
    f.puts ""
    f.puts "namespace tcc {"
    f.puts ""

    # Хелпер для экранирования спецсимволов для record syntax
    # В record syntax нужно экранировать: { } | < > " \
    f.puts "inline std::string escape_record(const std::string& s) {"
    f.puts "    std::string res;"
    f.puts "    for (char c : s) {"
    f.puts "        if (c == '{' || c == '}' || c == '|' || c == '<' || c == '>' || c == '\"' || c == '\\\\') {"
    f.puts "            res += '\\\\';"
    f.puts "        }"
    f.puts "        res += c;"
    f.puts "    }"
    f.puts "    return res;"
    f.puts "}"
    f.puts ""

    # 1. Функция получения цвета
    f.puts "inline std::string get_node_color(const std::string& op_type) {"
    f.puts "    if (false) {}"
    real_ops.each do |op|
      op_type = op['op_type']
      color = colors[op_type] || "#FFFFFF"
      f.puts "    else if (op_type == \"#{op_type}\") return \"#{color}\";"
    end
    f.puts "    else return \"#EEEEEE\";"
    f.puts "}"
    f.puts ""

    # 2. Функция генерации Record-лейбла
    # Формат: { Type | name: "val" | attr1: val | attr2: val }
    f.puts "inline std::string get_node_record_label(const ComputeNode& node) {"
    f.puts "    std::stringstream ss;"

    # Получаем тип операции
    f.puts "    std::string op_type = std::visit([](const auto& n) -> std::string {"
    f.puts "        using T = std::decay_t<decltype(n)>;"
    real_ops.each_with_index do |op, idx|
      cpp_name = op['cpp_name']
      onnx_type = op['op_type']
      is_first = (idx == 0)
      f.puts "        #{is_first ? 'if' : 'else if'} constexpr (std::is_same_v<T, #{cpp_name}>) return \"#{onnx_type}\";"
    end
    f.puts "        else return \"Unknown\";"
    f.puts "    }, node);"
    f.puts ""

    # Начало записи
    f.puts "    ss << \"{ \" << op_type;"

    f.puts "    std::visit([&](const auto& n) {"
    f.puts "        using T = std::decay_t<decltype(n)>;"

    real_ops.each_with_index do |op, idx|
      cpp_name = op['cpp_name']
      is_first = (idx == 0)

      f.puts "        #{is_first ? 'if' : 'else if'} constexpr (std::is_same_v<T, #{cpp_name}>) {"

      # Разделитель перед первым полем
      f.puts "            ss << \" | \";"

      # Имя узла
      f.puts "            if (!n.name.empty()) ss << \"name: \\\\\\\"\" << escape_record(n.name) << \"\\\\\\\" | \";"

      # Атрибуты
      (op['attributes'] || []).each do |attr|
        name = attr['name']
        type = attr['type']

        if type.start_with?('std::vector')
          # Вектор: [1, 2, 3]
          f.puts "            ss << \"#{name}: [\";"
          f.puts "            for(size_t i=0; i<n.#{name}.size(); ++i) {"
          f.puts "                if(i>0) ss << \", \";"
          f.puts "                ss << n.#{name}[i];"
          f.puts "            }"
          f.puts "            ss << \"] | \";"
        elsif type == 'std::string'
          f.puts "            ss << \"#{name}: \\\\\\\"\" << escape_record(n.#{name}) << \"\\\\\\\" | \";"
        elsif type == 'bool'
          f.puts "            ss << \"#{name}: \" << (n.#{name} ? \"true\" : \"false\") << \" | \";"
        else
          f.puts "            ss << \"#{name}: \" << n.#{name} << \" | \";"
        end
      end

      f.puts "        }"
    end

    f.puts "    }, node);"

    f.puts "    std::string result = ss.str();"
    f.puts "    if (result.size() > 3 && result.substr(result.size()-3) == \" | \") {"
    f.puts "        result = result.substr(0, result.size()-3);"
    f.puts "    }"
    f.puts "    result += \" }\";"
    f.puts "    return result;"
    f.puts "}"
    f.puts ""
    f.puts "} // namespace tcc"
  end

end
