#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'fileutils'

# ==============================================================================
# Configuration & Helpers
# ==============================================================================

SCRIPT_DIR = File.dirname(__FILE__)
JSON_FILE = File.join(SCRIPT_DIR, 'ops_def.json')
OUTPUT_HPP = File.join(SCRIPT_DIR, 'Graph', 'graph_gen.hpp')
OUTPUT_INL = File.join(SCRIPT_DIR, 'Graph', 'graph_gen_parser.inl')

# Маппинг типов JSON -> C++
# Маппинг типов JSON -> C++
def cpp_type(json_type)
  json_type
  # Если тип уже содержит пространство имен (например, std::string), возвращаем как есть
#   return json_type if json_type.include?('::')
#
#   case json_type
#   when 'bool' then 'bool'
#   when 'float' then 'float'
#   when 'int64_t' then 'int64_t'
#   when 'string' then 'std::string'
#   when /^vector<(.+)>$/
#     inner_type = $1
#     # Рекурсивно обрабатываем внутренний тип
#     return "std::vector<#{cpp_type(inner_type)}>"
#   else
#     raise "Unknown type: #{json_type}"
#   end
end

# ==============================================================================
# Generators: Header File (graph_gen.hpp)
# ==============================================================================

def write_header_start(f)
  f.puts "// AUTOGENERATED FILE. DO NOT EDIT MANUALLY."
  f.puts "// Generated by generate_nodes.rb from ops_def.json"
  f.puts "#pragma once"
  f.puts ""
  f.puts '#include <string>'
  f.puts '#include <vector>'
  f.puts '#include <variant>'
  f.puts '#include <cstdint>'
  f.puts ""
  f.puts "namespace tcc {"
  f.puts ""
  f.puts "using TensorID = std::string;"
  f.puts ""
end

def write_node_struct(f, op, common_fields)
  cpp_name = op['cpp_name']
  f.puts "struct #{cpp_name} {"

  # 1. Сначала пишем общие поля (из блока CommonFields)
  if common_fields
    common_fields.each do |field|
      type = cpp_type(field['type'])
      default = field['default']
      f.puts "    // Common field: #{field['name']}"
      f.puts "    #{type} #{field['name']} = #{default};"
    end
    f.puts "" unless op['attributes'].to_a.empty?
  end

  # 2. Затем специфичные атрибуты
  attrs = op['attributes'] || []
  attrs.each do |attr|
    type = cpp_type(attr['type'])
    default = attr['default']
    f.puts "    // Attribute: #{attr['name']}"
    f.puts "    #{type} #{attr['name']} = #{default};"
  end

  f.puts "};"
  f.puts ""
end

def write_variant_typedef(f, data)
  # Фильтруем CommonFields, чтобы не добавить его в variant
  real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }
  cpp_names = real_ops.map { |op| op['cpp_name'] }.join(', ')

  f.puts "// Variant containing all supported node types"
  f.puts "using ComputeNode = std::variant<#{cpp_names}>;"
  f.puts ""
end

def write_header_end(f)
  f.puts "} // namespace tcc"
end

# ==============================================================================
# Generators: Parser Implementation (graph_gen_parser.inl)
# ==============================================================================

def write_parser_start(f)
  f.puts "// AUTOGENERATED FILE. DO NOT EDIT MANUALLY."
  f.puts "// Generated by generate_nodes.rb from ops_def.json"
  f.puts "#include \"graph_gen.hpp\""
  f.puts "#include \"onnx/onnx.pb.h\""
  f.puts "#include <algorithm>"
  f.puts "#include <stdexcept>"
  f.puts ""
  f.puts "namespace tcc {"
  f.puts ""
end

def write_factory_function(f, op, common_fields)
  cpp_name = op['cpp_name']
  onnx_type = op['op_type']
  func_name = "create_#{onnx_type}_node"

  f.puts "inline ComputeNode #{func_name}(const onnx::NodeProto& proto) {"
  f.puts "    #{cpp_name} node;"

  # Инициализация общих полей
  if common_fields
    f.puts "    // Initialize common fields"
    common_fields.each do |field|
      field_name = field['name']
      if field_name == 'name'
        f.puts "    node.name = proto.name();"
      elsif field_name == 'input_tensors'
        f.puts "    node.input_tensors.assign(proto.input().begin(), proto.input().end());"
      elsif field_name == 'output_tensors'
        f.puts "    node.output_tensors.assign(proto.output().begin(), proto.output().end());"
      else
        # Если добавятся другие общие поля, потребуется логика для них
        f.puts "    // TODO: Initialize common field #{field_name}"
      end
    end
  end

  f.puts ""
  f.puts "    // Parse specific attributes"
  f.puts "    parse_attributes(node, proto);"
  f.puts "    return node;"
  f.puts "}"
  f.puts ""
end

def write_parse_attributes_function(f, op)
  cpp_name = op['cpp_name']
  attrs = op['attributes'] || []

  f.puts "inline void parse_attributes(#{cpp_name}& node, const onnx::NodeProto& proto) {"
  f.puts "    for (const auto& attr : proto.attribute()) {"
  f.puts "        const std::string& attr_name = attr.name();"

  if attrs.empty?
    f.puts "        // No specific attributes for #{op['op_type']}"
  else
    f.puts "        if (false) {} // Dummy start for else-if chain"

    attrs.each do |attr|
      attr_name_cpp = attr['name']
      attr_type = attr['type']

      f.puts "        else if (attr_name == \"#{attr_name_cpp}\") {"

      # Сопоставляем полные имена типов из JSON
      case attr_type
      when 'bool'
        f.puts "            node.#{attr_name_cpp} = attr.has_i() ? (attr.i() != 0) : false;"
      when 'float'
        f.puts "            node.#{attr_name_cpp} = attr.f();"
      when 'int64_t'
        f.puts "            node.#{attr_name_cpp} = attr.i();"
      when 'std::string'
        f.puts "            node.#{attr_name_cpp} = attr.s();"
      when /^std::vector<int64_t>$/
        f.puts "            node.#{attr_name_cpp}.assign(attr.ints().begin(), attr.ints().end());"
      when /^std::vector<float>$/
        f.puts "            node.#{attr_name_cpp}.assign(attr.floats().begin(), attr.floats().end());"
      when /^std::vector<std::string>$/
        f.puts "            // Parsing vector<string> requires custom logic if needed, skipping for now"
      else
        f.puts "            // Unknown attribute type: #{attr_type} for #{attr_name_cpp}"
      end
      # ^^^ Вот здесь был пропущен end для case

      f.puts "        }"
    end
    # ^^^ Вот здесь был пропущен end для each

    f.puts "        else {"
    f.puts "            // Ignore unknown attribute: \" + attr_name"
    f.puts "        }"
  end

  f.puts "    }"
  f.puts "}"
  f.puts ""
end

def write_dispatcher_function(f, data)
  real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }

  f.puts "inline ComputeNode create_node_from_proto(const onnx::NodeProto& proto) {"
  f.puts "    const std::string& op_type = proto.op_type();"

  real_ops.each do |op|
    onnx_type = op['op_type']
    f.puts "    if (op_type == \"#{onnx_type}\") return create_#{onnx_type}_node(proto);"
  end

  f.puts "    throw std::runtime_error(\"Unsupported operator: \" + op_type);"
  f.puts "}"
  f.puts ""
end

def write_parser_end(f)
  f.puts "} // namespace tcc"
end

# ==============================================================================
# Main Execution
# ==============================================================================

def main
  unless File.exist?(JSON_FILE)
    puts "Error: #{JSON_FILE} not found!"
    exit 1
  end

  puts "Reading #{JSON_FILE}..."
  data = JSON.parse(File.read(JSON_FILE))

  # Извлекаем общие поля
  common_def = data.find { |op| op['op_type'] == 'CommonFields' }
  common_fields = common_def ? common_def['fields'] : []

  if common_fields.empty?
    puts "Warning: No CommonFields defined in JSON. Nodes will only have specific attributes."
  else
    puts "Found CommonFields: #{common_fields.map { |f| f['name'] }.join(', ')}"
  end

  # Фильтруем список, убирая определение CommonFields из списка узлов
  real_ops = data.reject { |op| op['op_type'] == 'CommonFields' }

  # --- Generate Header ---
  puts "Generating #{OUTPUT_HPP}..."
  File.open(OUTPUT_HPP, 'w') do |f|
    write_header_start(f)
    real_ops.each { |op| write_node_struct(f, op, common_fields) }
    write_variant_typedef(f, data)
    write_header_end(f)
  end

  # --- Generate Parser ---
  puts "Generating #{OUTPUT_INL}..."
  File.open(OUTPUT_INL, 'w') do |f|
    write_parser_start(f)
    real_ops.each do |op|
      write_parse_attributes_function(f, op)
      write_factory_function(f, op, common_fields)
    end
    write_dispatcher_function(f, data)
    write_parser_end(f)
  end

  puts "Done! Generated files:"
  puts "  - #{OUTPUT_HPP}"
  puts "  - #{OUTPUT_INL}"
end

main
