// AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by generate_nodes.rb from ops_def.json
#pragma once

#include <string>
#include <vector>
#include <variant>
#include <cstdint>

namespace tcc {

using TensorID = std::string;

struct ConstantNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};

    // Attribute: value
    std::vector<float> value = {};
};

struct AddNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};
};

struct MulNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};
};

struct ReluNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};
};

struct MatmulNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};
};

struct GemmNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};

    // Attribute: transposeA
    bool transposeA = false;
    // Attribute: transposeB
    bool transposeB = false;
    // Attribute: alpha
    float alpha = 1.0;
    // Attribute: beta
    float beta = 1.0;
};

struct ConvNode {
    // Common field: name
    std::string name = "";
    // Common field: input_tensors
    std::vector<std::string> input_tensors = {};
    // Common field: output_tensors
    std::vector<std::string> output_tensors = {};

    // Attribute: strides
    std::vector<int64_t> strides = {1};
    // Attribute: pads
    std::vector<int64_t> pads = {0};
    // Attribute: dilations
    std::vector<int64_t> dilations = {1};
    // Attribute: group
    int64_t group = 1;
};

// Variant containing all supported node types
using ComputeNode = std::variant<ConstantNode, AddNode, MulNode, ReluNode, MatmulNode, GemmNode, ConvNode>;

} // namespace tcc
