// AUTOGENERATED FILE. DO NOT EDIT MANUALLY.
#pragma once

#include <string>
#include <vector>
#include <variant>
#include <cstdint>

namespace tcc {

using TensorID = std::string;

struct ConstantNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};

    std::vector<float> value = {};
};

struct AddNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};
};

struct MulNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};
};

struct ReluNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};
};

struct MatmulNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};
};

struct GemmNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};

    bool transposeA = false;
    bool transposeB = false;
    float alpha = 1.0;
    float beta = 1.0;
};

struct ConvNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};

    std::vector<int64_t> strides = {1};
    std::vector<int64_t> pads = {0};
    std::vector<int64_t> dilations = {1};
    int64_t group = 1;
};

struct FlattenNode {
    std::string name = "";
    std::vector<std::string> input_tensors = {};
    std::vector<std::string> output_tensors = {};

    int64_t axis = 1;
};

using ComputeNode = std::variant<ConstantNode, AddNode, MulNode, ReluNode, MatmulNode, GemmNode, ConvNode, FlattenNode>;

} // namespace tcc
