// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: onnx/onnx-data.proto

#include "onnx/onnx-data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_onnx_2fonnx_2ddata_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_MapProto_onnx_2fonnx_2ddata_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_onnx_2fonnx_2dml_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SparseTensorProto_onnx_2fonnx_2dml_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_onnx_2fonnx_2dml_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_TensorProto_onnx_2fonnx_2dml_2eproto;
namespace onnx {
class SequenceProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SequenceProto> _instance;
} _SequenceProto_default_instance_;
class MapProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MapProto> _instance;
} _MapProto_default_instance_;
class OptionalProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<OptionalProto> _instance;
} _OptionalProto_default_instance_;
}  // namespace onnx
static void InitDefaultsscc_info_MapProto_onnx_2fonnx_2ddata_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::onnx::_SequenceProto_default_instance_;
    new (ptr) ::onnx::SequenceProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::onnx::_MapProto_default_instance_;
    new (ptr) ::onnx::MapProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::onnx::_OptionalProto_default_instance_;
    new (ptr) ::onnx::OptionalProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::onnx::SequenceProto::InitAsDefaultInstance();
  ::onnx::MapProto::InitAsDefaultInstance();
  ::onnx::OptionalProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_MapProto_onnx_2fonnx_2ddata_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_MapProto_onnx_2fonnx_2ddata_2eproto}, {
      &scc_info_TensorProto_onnx_2fonnx_2dml_2eproto.base,
      &scc_info_SparseTensorProto_onnx_2fonnx_2dml_2eproto.base,}};

namespace onnx {
bool SequenceProto_DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> SequenceProto_DataType_strings[6] = {};

static const char SequenceProto_DataType_names[] =
  "MAP"
  "OPTIONAL"
  "SEQUENCE"
  "SPARSE_TENSOR"
  "TENSOR"
  "UNDEFINED";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry SequenceProto_DataType_entries[] = {
  { {SequenceProto_DataType_names + 0, 3}, 4 },
  { {SequenceProto_DataType_names + 3, 8}, 5 },
  { {SequenceProto_DataType_names + 11, 8}, 3 },
  { {SequenceProto_DataType_names + 19, 13}, 2 },
  { {SequenceProto_DataType_names + 32, 6}, 1 },
  { {SequenceProto_DataType_names + 38, 9}, 0 },
};

static const int SequenceProto_DataType_entries_by_number[] = {
  5, // 0 -> UNDEFINED
  4, // 1 -> TENSOR
  3, // 2 -> SPARSE_TENSOR
  2, // 3 -> SEQUENCE
  0, // 4 -> MAP
  1, // 5 -> OPTIONAL
};

const std::string& SequenceProto_DataType_Name(
    SequenceProto_DataType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          SequenceProto_DataType_entries,
          SequenceProto_DataType_entries_by_number,
          6, SequenceProto_DataType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      SequenceProto_DataType_entries,
      SequenceProto_DataType_entries_by_number,
      6, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     SequenceProto_DataType_strings[idx].get();
}
bool SequenceProto_DataType_Parse(
    const std::string& name, SequenceProto_DataType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      SequenceProto_DataType_entries, 6, name, &int_value);
  if (success) {
    *value = static_cast<SequenceProto_DataType>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr SequenceProto_DataType SequenceProto::UNDEFINED;
constexpr SequenceProto_DataType SequenceProto::TENSOR;
constexpr SequenceProto_DataType SequenceProto::SPARSE_TENSOR;
constexpr SequenceProto_DataType SequenceProto::SEQUENCE;
constexpr SequenceProto_DataType SequenceProto::MAP;
constexpr SequenceProto_DataType SequenceProto::OPTIONAL;
constexpr SequenceProto_DataType SequenceProto::DataType_MIN;
constexpr SequenceProto_DataType SequenceProto::DataType_MAX;
constexpr int SequenceProto::DataType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool OptionalProto_DataType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> OptionalProto_DataType_strings[6] = {};

static const char OptionalProto_DataType_names[] =
  "MAP"
  "OPTIONAL"
  "SEQUENCE"
  "SPARSE_TENSOR"
  "TENSOR"
  "UNDEFINED";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry OptionalProto_DataType_entries[] = {
  { {OptionalProto_DataType_names + 0, 3}, 4 },
  { {OptionalProto_DataType_names + 3, 8}, 5 },
  { {OptionalProto_DataType_names + 11, 8}, 3 },
  { {OptionalProto_DataType_names + 19, 13}, 2 },
  { {OptionalProto_DataType_names + 32, 6}, 1 },
  { {OptionalProto_DataType_names + 38, 9}, 0 },
};

static const int OptionalProto_DataType_entries_by_number[] = {
  5, // 0 -> UNDEFINED
  4, // 1 -> TENSOR
  3, // 2 -> SPARSE_TENSOR
  2, // 3 -> SEQUENCE
  0, // 4 -> MAP
  1, // 5 -> OPTIONAL
};

const std::string& OptionalProto_DataType_Name(
    OptionalProto_DataType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          OptionalProto_DataType_entries,
          OptionalProto_DataType_entries_by_number,
          6, OptionalProto_DataType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      OptionalProto_DataType_entries,
      OptionalProto_DataType_entries_by_number,
      6, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     OptionalProto_DataType_strings[idx].get();
}
bool OptionalProto_DataType_Parse(
    const std::string& name, OptionalProto_DataType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      OptionalProto_DataType_entries, 6, name, &int_value);
  if (success) {
    *value = static_cast<OptionalProto_DataType>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr OptionalProto_DataType OptionalProto::UNDEFINED;
constexpr OptionalProto_DataType OptionalProto::TENSOR;
constexpr OptionalProto_DataType OptionalProto::SPARSE_TENSOR;
constexpr OptionalProto_DataType OptionalProto::SEQUENCE;
constexpr OptionalProto_DataType OptionalProto::MAP;
constexpr OptionalProto_DataType OptionalProto::OPTIONAL;
constexpr OptionalProto_DataType OptionalProto::DataType_MIN;
constexpr OptionalProto_DataType OptionalProto::DataType_MAX;
constexpr int OptionalProto::DataType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void SequenceProto::InitAsDefaultInstance() {
}
class SequenceProto::_Internal {
 public:
  using HasBits = decltype(std::declval<SequenceProto>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_elem_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

void SequenceProto::clear_tensor_values() {
  tensor_values_.Clear();
}
void SequenceProto::clear_sparse_tensor_values() {
  sparse_tensor_values_.Clear();
}
SequenceProto::SequenceProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena),
  tensor_values_(arena),
  sparse_tensor_values_(arena),
  sequence_values_(arena),
  map_values_(arena),
  optional_values_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:onnx.SequenceProto)
}
SequenceProto::SequenceProto(const SequenceProto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_),
      tensor_values_(from.tensor_values_),
      sparse_tensor_values_(from.sparse_tensor_values_),
      sequence_values_(from.sequence_values_),
      map_values_(from.map_values_),
      optional_values_(from.optional_values_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_name()) {
    name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  elem_type_ = from.elem_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.SequenceProto)
}

void SequenceProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  elem_type_ = 0;
}

SequenceProto::~SequenceProto() {
  // @@protoc_insertion_point(destructor:onnx.SequenceProto)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void SequenceProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SequenceProto::ArenaDtor(void* object) {
  SequenceProto* _this = reinterpret_cast< SequenceProto* >(object);
  (void)_this;
}
void SequenceProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SequenceProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SequenceProto& SequenceProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  return *internal_default_instance();
}


void SequenceProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.SequenceProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tensor_values_.Clear();
  sparse_tensor_values_.Clear();
  sequence_values_.Clear();
  map_values_.Clear();
  optional_values_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    name_.ClearNonDefaultToEmpty();
  }
  elem_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* SequenceProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional int32 elem_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_elem_type(&has_bits);
          elem_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .onnx.TensorProto tensor_values = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_tensor_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sparse_tensor_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .onnx.SequenceProto sequence_values = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sequence_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .onnx.MapProto map_values = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_map_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .onnx.OptionalProto optional_values = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_optional_values(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<58>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SequenceProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:onnx.SequenceProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional int32 elem_type = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_elem_type(), target);
  }

  // repeated .onnx.TensorProto tensor_values = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_tensor_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_tensor_values(i), target, stream);
  }

  // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sparse_tensor_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(4, this->_internal_sparse_tensor_values(i), target, stream);
  }

  // repeated .onnx.SequenceProto sequence_values = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_sequence_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, this->_internal_sequence_values(i), target, stream);
  }

  // repeated .onnx.MapProto map_values = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_map_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, this->_internal_map_values(i), target, stream);
  }

  // repeated .onnx.OptionalProto optional_values = 7;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_optional_values_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, this->_internal_optional_values(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onnx.SequenceProto)
  return target;
}

size_t SequenceProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.SequenceProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .onnx.TensorProto tensor_values = 3;
  total_size += 1UL * this->_internal_tensor_values_size();
  for (const auto& msg : this->tensor_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .onnx.SparseTensorProto sparse_tensor_values = 4;
  total_size += 1UL * this->_internal_sparse_tensor_values_size();
  for (const auto& msg : this->sparse_tensor_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .onnx.SequenceProto sequence_values = 5;
  total_size += 1UL * this->_internal_sequence_values_size();
  for (const auto& msg : this->sequence_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .onnx.MapProto map_values = 6;
  total_size += 1UL * this->_internal_map_values_size();
  for (const auto& msg : this->map_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .onnx.OptionalProto optional_values = 7;
  total_size += 1UL * this->_internal_optional_values_size();
  for (const auto& msg : this->optional_values_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional int32 elem_type = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_elem_type());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SequenceProto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const SequenceProto*>(
      &from));
}

void SequenceProto::MergeFrom(const SequenceProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.SequenceProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tensor_values_.MergeFrom(from.tensor_values_);
  sparse_tensor_values_.MergeFrom(from.sparse_tensor_values_);
  sequence_values_.MergeFrom(from.sequence_values_);
  map_values_.MergeFrom(from.map_values_);
  optional_values_.MergeFrom(from.optional_values_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      elem_type_ = from.elem_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void SequenceProto::CopyFrom(const SequenceProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.SequenceProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SequenceProto::IsInitialized() const {
  return true;
}

void SequenceProto::InternalSwap(SequenceProto* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  tensor_values_.InternalSwap(&other->tensor_values_);
  sparse_tensor_values_.InternalSwap(&other->sparse_tensor_values_);
  sequence_values_.InternalSwap(&other->sequence_values_);
  map_values_.InternalSwap(&other->map_values_);
  optional_values_.InternalSwap(&other->optional_values_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(elem_type_, other->elem_type_);
}

std::string SequenceProto::GetTypeName() const {
  return "onnx.SequenceProto";
}


// ===================================================================

void MapProto::InitAsDefaultInstance() {
  ::onnx::_MapProto_default_instance_._instance.get_mutable()->values_ = const_cast< ::onnx::SequenceProto*>(
      ::onnx::SequenceProto::internal_default_instance());
}
class MapProto::_Internal {
 public:
  using HasBits = decltype(std::declval<MapProto>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_key_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::onnx::SequenceProto& values(const MapProto* msg);
  static void set_has_values(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

const ::onnx::SequenceProto&
MapProto::_Internal::values(const MapProto* msg) {
  return *msg->values_;
}
MapProto::MapProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena),
  keys_(arena),
  string_keys_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:onnx.MapProto)
}
MapProto::MapProto(const MapProto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_),
      keys_(from.keys_),
      string_keys_(from.string_keys_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_name()) {
    name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  if (from._internal_has_values()) {
    values_ = new ::onnx::SequenceProto(*from.values_);
  } else {
    values_ = nullptr;
  }
  key_type_ = from.key_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.MapProto)
}

void MapProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&values_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&key_type_) -
      reinterpret_cast<char*>(&values_)) + sizeof(key_type_));
}

MapProto::~MapProto() {
  // @@protoc_insertion_point(destructor:onnx.MapProto)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void MapProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete values_;
}

void MapProto::ArenaDtor(void* object) {
  MapProto* _this = reinterpret_cast< MapProto* >(object);
  (void)_this;
}
void MapProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MapProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MapProto& MapProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  return *internal_default_instance();
}


void MapProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.MapProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  keys_.Clear();
  string_keys_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(values_ != nullptr);
      values_->Clear();
    }
  }
  key_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* MapProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional int32 key_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_key_type(&has_bits);
          key_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated int64 keys = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_keys(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<24>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt64Parser(_internal_mutable_keys(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated bytes string_keys = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_string_keys();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else goto handle_unusual;
        continue;
      // optional .onnx.SequenceProto values = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_values(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MapProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:onnx.MapProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional int32 key_type = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_key_type(), target);
  }

  // repeated int64 keys = 3;
  for (int i = 0, n = this->_internal_keys_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(3, this->_internal_keys(i), target);
  }

  // repeated bytes string_keys = 4;
  for (int i = 0, n = this->_internal_string_keys_size(); i < n; i++) {
    const auto& s = this->_internal_string_keys(i);
    target = stream->WriteBytes(4, s, target);
  }

  // optional .onnx.SequenceProto values = 5;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::values(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onnx.MapProto)
  return target;
}

size_t MapProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.MapProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int64 keys = 3;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int64Size(this->keys_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_keys_size());
    total_size += data_size;
  }

  // repeated bytes string_keys = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(string_keys_.size());
  for (int i = 0, n = string_keys_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
      string_keys_.Get(i));
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional .onnx.SequenceProto values = 5;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *values_);
    }

    // optional int32 key_type = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_key_type());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapProto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const MapProto*>(
      &from));
}

void MapProto::MergeFrom(const MapProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.MapProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  keys_.MergeFrom(from.keys_);
  string_keys_.MergeFrom(from.string_keys_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_values()->::onnx::SequenceProto::MergeFrom(from._internal_values());
    }
    if (cached_has_bits & 0x00000004u) {
      key_type_ = from.key_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void MapProto::CopyFrom(const MapProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.MapProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapProto::IsInitialized() const {
  return true;
}

void MapProto::InternalSwap(MapProto* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  keys_.InternalSwap(&other->keys_);
  string_keys_.InternalSwap(&other->string_keys_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MapProto, key_type_)
      + sizeof(MapProto::key_type_)
      - PROTOBUF_FIELD_OFFSET(MapProto, values_)>(
          reinterpret_cast<char*>(&values_),
          reinterpret_cast<char*>(&other->values_));
}

std::string MapProto::GetTypeName() const {
  return "onnx.MapProto";
}


// ===================================================================

void OptionalProto::InitAsDefaultInstance() {
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->tensor_value_ = const_cast< ::onnx::TensorProto*>(
      ::onnx::TensorProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->sparse_tensor_value_ = const_cast< ::onnx::SparseTensorProto*>(
      ::onnx::SparseTensorProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->sequence_value_ = const_cast< ::onnx::SequenceProto*>(
      ::onnx::SequenceProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->map_value_ = const_cast< ::onnx::MapProto*>(
      ::onnx::MapProto::internal_default_instance());
  ::onnx::_OptionalProto_default_instance_._instance.get_mutable()->optional_value_ = const_cast< ::onnx::OptionalProto*>(
      ::onnx::OptionalProto::internal_default_instance());
}
class OptionalProto::_Internal {
 public:
  using HasBits = decltype(std::declval<OptionalProto>()._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_elem_type(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static const ::onnx::TensorProto& tensor_value(const OptionalProto* msg);
  static void set_has_tensor_value(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static const ::onnx::SparseTensorProto& sparse_tensor_value(const OptionalProto* msg);
  static void set_has_sparse_tensor_value(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::onnx::SequenceProto& sequence_value(const OptionalProto* msg);
  static void set_has_sequence_value(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::onnx::MapProto& map_value(const OptionalProto* msg);
  static void set_has_map_value(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::onnx::OptionalProto& optional_value(const OptionalProto* msg);
  static void set_has_optional_value(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

const ::onnx::TensorProto&
OptionalProto::_Internal::tensor_value(const OptionalProto* msg) {
  return *msg->tensor_value_;
}
const ::onnx::SparseTensorProto&
OptionalProto::_Internal::sparse_tensor_value(const OptionalProto* msg) {
  return *msg->sparse_tensor_value_;
}
const ::onnx::SequenceProto&
OptionalProto::_Internal::sequence_value(const OptionalProto* msg) {
  return *msg->sequence_value_;
}
const ::onnx::MapProto&
OptionalProto::_Internal::map_value(const OptionalProto* msg) {
  return *msg->map_value_;
}
const ::onnx::OptionalProto&
OptionalProto::_Internal::optional_value(const OptionalProto* msg) {
  return *msg->optional_value_;
}
void OptionalProto::clear_tensor_value() {
  if (tensor_value_ != nullptr) tensor_value_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
void OptionalProto::clear_sparse_tensor_value() {
  if (sparse_tensor_value_ != nullptr) sparse_tensor_value_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
OptionalProto::OptionalProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:onnx.OptionalProto)
}
OptionalProto::OptionalProto(const OptionalProto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_name()) {
    name_.SetLite(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_name(),
      GetArena());
  }
  if (from._internal_has_tensor_value()) {
    tensor_value_ = new ::onnx::TensorProto(*from.tensor_value_);
  } else {
    tensor_value_ = nullptr;
  }
  if (from._internal_has_sparse_tensor_value()) {
    sparse_tensor_value_ = new ::onnx::SparseTensorProto(*from.sparse_tensor_value_);
  } else {
    sparse_tensor_value_ = nullptr;
  }
  if (from._internal_has_sequence_value()) {
    sequence_value_ = new ::onnx::SequenceProto(*from.sequence_value_);
  } else {
    sequence_value_ = nullptr;
  }
  if (from._internal_has_map_value()) {
    map_value_ = new ::onnx::MapProto(*from.map_value_);
  } else {
    map_value_ = nullptr;
  }
  if (from._internal_has_optional_value()) {
    optional_value_ = new ::onnx::OptionalProto(*from.optional_value_);
  } else {
    optional_value_ = nullptr;
  }
  elem_type_ = from.elem_type_;
  // @@protoc_insertion_point(copy_constructor:onnx.OptionalProto)
}

void OptionalProto::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&tensor_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&elem_type_) -
      reinterpret_cast<char*>(&tensor_value_)) + sizeof(elem_type_));
}

OptionalProto::~OptionalProto() {
  // @@protoc_insertion_point(destructor:onnx.OptionalProto)
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

void OptionalProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete tensor_value_;
  if (this != internal_default_instance()) delete sparse_tensor_value_;
  if (this != internal_default_instance()) delete sequence_value_;
  if (this != internal_default_instance()) delete map_value_;
  if (this != internal_default_instance()) delete optional_value_;
}

void OptionalProto::ArenaDtor(void* object) {
  OptionalProto* _this = reinterpret_cast< OptionalProto* >(object);
  (void)_this;
}
void OptionalProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void OptionalProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const OptionalProto& OptionalProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MapProto_onnx_2fonnx_2ddata_2eproto.base);
  return *internal_default_instance();
}


void OptionalProto::Clear() {
// @@protoc_insertion_point(message_clear_start:onnx.OptionalProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(tensor_value_ != nullptr);
      tensor_value_->Clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(sparse_tensor_value_ != nullptr);
      sparse_tensor_value_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(sequence_value_ != nullptr);
      sequence_value_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(map_value_ != nullptr);
      map_value_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(optional_value_ != nullptr);
      optional_value_->Clear();
    }
  }
  elem_type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* OptionalProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // optional string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional int32 elem_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _Internal::set_has_elem_type(&has_bits);
          elem_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .onnx.TensorProto tensor_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_tensor_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_sparse_tensor_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .onnx.SequenceProto sequence_value = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_sequence_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .onnx.MapProto map_value = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_map_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .onnx.OptionalProto optional_value = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_optional_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* OptionalProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:onnx.OptionalProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // optional int32 elem_type = 2;
  if (cached_has_bits & 0x00000040u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_elem_type(), target);
  }

  // optional .onnx.TensorProto tensor_value = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::tensor_value(this), target, stream);
  }

  // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::sparse_tensor_value(this), target, stream);
  }

  // optional .onnx.SequenceProto sequence_value = 5;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::sequence_value(this), target, stream);
  }

  // optional .onnx.MapProto map_value = 6;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::map_value(this), target, stream);
  }

  // optional .onnx.OptionalProto optional_value = 7;
  if (cached_has_bits & 0x00000020u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::optional_value(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:onnx.OptionalProto)
  return target;
}

size_t OptionalProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:onnx.OptionalProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    // optional string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_name());
    }

    // optional .onnx.TensorProto tensor_value = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *tensor_value_);
    }

    // optional .onnx.SparseTensorProto sparse_tensor_value = 4;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *sparse_tensor_value_);
    }

    // optional .onnx.SequenceProto sequence_value = 5;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *sequence_value_);
    }

    // optional .onnx.MapProto map_value = 6;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *map_value_);
    }

    // optional .onnx.OptionalProto optional_value = 7;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *optional_value_);
    }

    // optional int32 elem_type = 2;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
          this->_internal_elem_type());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void OptionalProto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const OptionalProto*>(
      &from));
}

void OptionalProto::MergeFrom(const OptionalProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:onnx.OptionalProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000007fu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_tensor_value()->::onnx::TensorProto::MergeFrom(from._internal_tensor_value());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_sparse_tensor_value()->::onnx::SparseTensorProto::MergeFrom(from._internal_sparse_tensor_value());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_mutable_sequence_value()->::onnx::SequenceProto::MergeFrom(from._internal_sequence_value());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_mutable_map_value()->::onnx::MapProto::MergeFrom(from._internal_map_value());
    }
    if (cached_has_bits & 0x00000020u) {
      _internal_mutable_optional_value()->::onnx::OptionalProto::MergeFrom(from._internal_optional_value());
    }
    if (cached_has_bits & 0x00000040u) {
      elem_type_ = from.elem_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OptionalProto::CopyFrom(const OptionalProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:onnx.OptionalProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OptionalProto::IsInitialized() const {
  return true;
}

void OptionalProto::InternalSwap(OptionalProto* other) {
  using std::swap;
  _internal_metadata_.Swap<std::string>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(OptionalProto, elem_type_)
      + sizeof(OptionalProto::elem_type_)
      - PROTOBUF_FIELD_OFFSET(OptionalProto, tensor_value_)>(
          reinterpret_cast<char*>(&tensor_value_),
          reinterpret_cast<char*>(&other->tensor_value_));
}

std::string OptionalProto::GetTypeName() const {
  return "onnx.OptionalProto";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace onnx
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::onnx::SequenceProto* Arena::CreateMaybeMessage< ::onnx::SequenceProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::onnx::SequenceProto >(arena);
}
template<> PROTOBUF_NOINLINE ::onnx::MapProto* Arena::CreateMaybeMessage< ::onnx::MapProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::onnx::MapProto >(arena);
}
template<> PROTOBUF_NOINLINE ::onnx::OptionalProto* Arena::CreateMaybeMessage< ::onnx::OptionalProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::onnx::OptionalProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
